# Site settings
name: jax777
email: jax777@qq.com
author: jax777
url: https://www.jax777.win
github: https://github.com/jax777/
baseurl: ""
description: Actually, less is more!
meta_description: jax777;个人博客
motto: It's our wits that make us men.
banner: 年轻人不要总熬夜

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jax777

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

